version: '2'
services:
  apache:
    depends_on:
      - pgadmin
      - syncope-console
      - syncope-enduser
    image: docker.io/bitnami/apache:2.4-debian-10
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./apache/httpd.conf:/opt/bitnami/apache/conf/httpd.conf:ro
      - ./apache/my_vhost.conf:/vhosts/my_vhost.conf:ro
      - ./webserver:/app:ro
      - ../SSLcertificates:/certs:ro

  db:
    image: timescale/timescaledb:2.0.0-pg12
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:5.1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: delfi@tudelft.nl
      # this is the initial user password, change after first login
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin/pgpassfile:/pgadmin4/pgpassfile.json:ro
    links:
      - "db:pgsql-server"

  syncope: 
    depends_on:
      - db
    image: apache/syncope:2.1.8
    restart: always
    environment:
       DBMS: postgresql
       DB_URL: jdbc:postgresql://db:5432/syncope
       DB_USER: admin
       DB_PASSWORD: secret
       DB_POOL_MAX: 10
       DB_POOL_MIN: 2
       OPENJPA_REMOTE_COMMIT: sjvm
    ports:
      - 8080:8080
    volumes:
      - ./syncope/security.properties:/etc/apache-syncope/security.properties:ro
      - ./syncope/mail.properties:/etc/apache-syncope/mail.properties:ro

  syncope-console:
    depends_on:
      - syncope
    image: apache/syncope-console:2.1.8
    restart: always
    environment:
       CORE_SCHEME: http
       CORE_HOST: syncope
       CORE_PORT: 8080
    volumes:
            - ./syncope-console/console.properties:/etc/apache-syncope/console.properties:ro

  syncope-enduser:
    depends_on:
      - syncope
    image: apache/syncope-enduser:2.1.8
    restart: always
    environment:
      CORE_SCHEME: http
      CORE_HOST: syncope
      CORE_PORT: 8080
      DOMAIN: Master
    ports:
     - 8081:8080
    volumes:
     - ./syncope-enduser/enduser.properties:/etc/apache-syncope/enduser.properties:ro
     - ./syncope-enduser/customTemplate.json:/etc/apache-syncope/customTemplate.json:ro

