version: '2'
services:
  apache:
    depends_on:
      - pgadmin
    image: docker.io/bitnami/apache:2.4-debian-10
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./apache/httpd.conf:/opt/bitnami/apache/conf/httpd.conf:ro
      - ./apache/my_vhost.conf:/vhosts/my_vhost.conf:ro
      - ./apache/webserver:/app:ro
      # TODO: for production, map an external folder with certificates
      #- ../SSLcertificates:/certs:ro

  db:
    image: timescale/timescaledb:2.0.0-pg12
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    # TODO: remove the port statement for production
    # leave the database only accessible from the docker environment
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:5.1
    restart: always
    environment:
      # TODO: set your admin email
      PGADMIN_DEFAULT_EMAIL: delfi@tudelft.nl
      # this is the initial user password, change after first login
      # TODO: this is only the initial password, update it in th eproduction container
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin/pgpassfile:/pgadmin4/pgpassfile.json:ro
    links:
      - "db:pgsql-server"
